use_frameworks!

platform :ios, '9.0'

target 'HFTestPirvate_Example' do
  pod 'HFTestPirvate', :path => '../'

  target 'HFTestPirvate_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
